### ISSUE TITLE
Update Color Palette

### ISSUE THREAD

**Issue by alexrchies** [Stratio/egeo-ui-base#54]
The status color palette has been modified, so is mandatory to update it as the following images:

Former scheme:
![old_scheme](https://cloud.githubusercontent.com/assets/7441029/26353702/e9214dd6-3fc1-11e7-810a-ede6432ee8a6.png)

Updated scheme:
![new_scheme](https://cloud.githubusercontent.com/assets/7441029/26353708/f3666768-3fc1-11e7-80d3-0a5686bdc08e.png)

You can take those new values straight from the [prototype](https://zpl.io/Z2vrOTu).

**Comment by alexrchies** [comment]
@abrahamnavas I need the RGB codes as well and these should be also added to the Zeplin document.

**Comment by abrahamnavas** [comment]
There you are:

`#acc952  > rgb 172 201 82`
`#b6c97b > rgb 182 201 123`
`#96b048 > rgb 150 176 72`
`#fdbd2b > rgb 253 189 43`
`#fccd5d > rgb 252 205 93`
`#e3aa27 > rgb 227 170 39`
`#db030e > rgb 219 3 14`
`#db2e37 > rgb 219 46 55`
`#c2020c > rgb 194 2 12`

**Comment by abrahamnavas** [comment]
Tertiary colors:
![tertiary_colors](https://cloud.githubusercontent.com/assets/7441029/26442009/0e914fe0-4133-11e7-9776-4d7d43da12a7.png)


`#d7c200 > rgb 215 194 0`
`#00d9df > rgb 0 217 223`
`#a7eb1e > rgb 167 235 30`
